- name: Allow release-info to change for APT repositories
  command: apt-get update -y --allow-releaseinfo-change

- name: Upgrade all packages ({{ ansible_facts['distribution'] }})
  apt:
    name: '*'
    state: latest
    only_upgrade: yes
    update_cache: yes