#!/usr/bin/env ansible-playbook

---
- hosts: all,localhost
  connection: local
  become: true

  tasks:
    - name: Including main vars for the play
      include_vars: vars/main.yml

    - name: Including distribution specific tasks for updating packages
      include_tasks: "tasks/update-packages/{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"

    - name: Including tasks to configure ansible-pull
      include_tasks: "tasks/ansible-pull/main.yml"
