#!/usr/bin/env ansible-playbook

---
- hosts: all,localhost
  connection: local
  strategy: free
  become: true

  tasks:
    - name: Ending execution on GitHub action host
      meta: end_host
      when:
        - ansible_distribution == 'Alpine'

    - name: Download required roles
      delegate_to: localhost
      command: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml
      changed_when: false

    - name: Including main vars for the play
      include_vars: vars/main.yml

    - name: Including distribution specific tasks for updating packages
      include_tasks: "{{ item }}"
      with_first_found:
        - "tasks/update-packages/{{ ansible_distribution }}.yml"
        - "tasks/update-packages/{{ ansible_os_family }}.yml"
        - "tasks/update-packages/default.yml"

    - name: Including tasks to configure ansible-pull
      include_tasks: "tasks/ansible-pull/main.yml"

    - name: Including tasks to configure ssh-access
      include_tasks: "tasks/ssh-access/main.yml"
