- name: "ansible-pull | Including distribution specific package list"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/ansible-pull/{{ ansible_distribution }}.yml"
    - "vars/ansible-pull/{{ ansible_os_family }}.yml"
    - "vars/ansible-pull/default.yml"

- name: "ansible-pull | Ensure needed packages are installed"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_pull_needed_packages }}"

- name: "ansible-pull | Create ansible user"
  user:
    name: ansible
    state: present
    system: true
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    create_home: yes
    home: /home/ansible

- name: "ansible-pull | Grant ansible user permissions to sudo"
  lineinfile:
    path: /etc/sudoers.d/ansible
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: "0440"
    create: yes
    validate: 'visudo -cf %s'

- name: "ansible-pull | Ensure that files in /etc/sudoers.d are included"
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "visudo -cf %s"

- name: "ansible-pull | Enable ansible logging"
  lineinfile:
    dest: /etc/ansible/ansible.cfg
    line: "log_path = /var/log/ansible.log"
    insertafter: '^#log_path'
    state: present

- name: "ansible-pull | Configure logrotation for ansible.log"
  template:
    src: templates/etc/logrotate.d/ansible-pull.j2
    dest: /etc/logrotate.d/ansible-pull
    owner: root
    group: root
    mode: "0644"

- name: "ansible-pull | Add cronjob to execute ansible-pull"
  cron:
    name: ansible-pull
    minute: "*/{{ ansible_pull_every_minutes }}"
    user: ansible
    job: "ansible-pull --url https://github.com/stearz/host-control.git \
                       --sleep 60 \
                       --checkout {{ ansible_pull_branch }} \
                       --accept-host-key \
                       --clean \
                       --force"
    cron_file: ansible-pull
