- name: "ansible-pull | Including distribution specific package list"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/ansible-pull/{{ ansible_distribution }}.yml"
    - "vars/ansible-pull/{{ ansible_os_family }}.yml"
    - "vars/ansible-pull/default.yml"

- name: "ansible-pull | Ensure needed packages are installed"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_pull_needed_packages }}"

- name: "ansible-pull | Create ansible user"
  user:
    name: ansible
    state: present
    system: true
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    create_home: yes
    home: "{{ ansible_pull_user_home_dir }}"
    group: "{{ ansible_pull_group_ansible_user | default(omit) }}"
    groups: "{{ ansible_pull_groups_ansible_user | default(omit) }}"
    append: yes

- name: "ansible-pull | Grant ansible user permissions to sudo"
  lineinfile:
    path: /etc/sudoers.d/ansible
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: "0440"
    create: yes
    validate: 'visudo -cf %s'

- name: "ansible-pull | Ensure that files in /etc/sudoers.d are included"
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "visudo -cf %s"

- name: "ansible-pull | Get stats of /var/log/ansible.log"
  ansible.builtin.stat:
    path: /var/log/ansible.log
  register: stat_ansible_log

- name: "ansible-pull | Creating ansible log file"
  file:
    path: /var/log/ansible.log
    owner: ansible
    group: "{{ ansible_pull_group_root_name }}"
    mode: "0640"
    state: touch
  when: not stat_ansible_log.stat.exists

- name: "ansible-pull | Ensure /etc/ansible exists"
  file:
    path: /etc/ansible
    state: directory
    owner: root
    group: "{{ ansible_pull_group_root_name }}"
    mode: "0755"

- name: "ansible-pull | Templating ansible.cfg to enable logging"
  template:
    src: "templates/etc/ansible/ansible.cfg.j2"
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: "{{ ansible_pull_group_root_name }}"
    mode: "0644"

- name: "ansible-pull | Configure logrotation for ansible.log"
  template:
    src: "templates{{ ansible_pull_logrotate_config_file }}.j2"
    dest: "{{ ansible_pull_logrotate_config_file }}"
    owner: root
    group: "{{ ansible_pull_group_root_name }}"
    mode: "0644"

- name: "ansible-pull | Clean-up old cron-file"
  file:
    path: /etc/cron.d/ansible-pull
    state: absent

- name: "ansible-pull | Add cronjob to execute ansible-pull"
  cron:
    name: ansible-pull
    minute: "*/{{ ansible_pull_every_minutes }}"
    user: ansible
    job: "ansible-pull --url https://github.com/stearz/host-control.git \
                       --sleep 60 \
                       --checkout {{ ansible_pull_branch }} \
                       --accept-host-key \
                       --clean \
                       --force \
                       local.yml"
