---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: instance-centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    privileged: true
  - name: instance-debian
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
    privileged: true
  - name: instance-ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
